### ISSUE TITLE
Al visualizar la foto desde la publicacion esta esta cortada y no se puede ver completa. Solo se puede hacer scroll en el modal.

### ISSUE THREAD

**Issue by Ignaciowelk** [Holocruxe-Galaxy/Mustafar#83]
![Al visualizar la foto desde la publicacion esta esta cortada y no se puede ver completa](https://github.com/Holocruxe-Galaxy/Mustafar/assets/134174872/58e8c71f-0e12-4180-94a2-49ce097f31f1)

1-Estar posicionado en el Diario.
2-Escribir un mensaje y hacer click en el boton para adjuntar una imagen y seleccionar una.
3-Click en publicar.
4-Al punlicar se el mensaje hacer click en la fecha precente en el mismo para desplegar la imagen.
5-Al desplegarse la imagen esta se ve cortada en los bordes superior e inferior y no se le da al usuario la opcion de poder visualizar la imagen completa.

**Comment by Emicon97** [comment]
This has been fixed in the modal but requires to be fixed in the entry view as well.
